#!/bin/sh

generate_cloud() {
  for dir in "$1"/*/; do
    [ -d "$dir" ] || continue # skip if it's not a directory
    count=$(find "$dir" -type f -name "*.md" | wc -l)

    # Skip directories that don't contain .md files
    if [ "$count" -gt 0 ]; then
      # Set font size based on the number of .md files
      if [ "$count" -ge 200 ]; then
        size=40
      elif [ "$count" -ge 150 ]; then
        size=30
      elif [ "$count" -ge 100 ]; then
        size=20
      elif [ "$count" -ge 50 ]; then
        size=15
      else
        size=15
      fi

      dir_name=$(basename "$dir")
      echo -n "<a href=\"$dir\"><span style=\"font-size: ${size}px;\">$dir_name $count</span></a> | " >> i.md 
    fi

    # Recursively process subdirectories
    generate_cloud "$dir"
  done
}

# Start with the current directory
generate_cloud "."

